// LeaderboardView — the DSO forecaster leaderboard workbench (Phase 3).
//
// Self-serve "compare-and-pick" over the v0.1.5 leaderboard API: paste a demand
// history + four bounded knobs, run, and see every registered forecaster ranked
// PROBABILISTICALLY (CRPS + interval coverage) with a beats-naive credibility
// badge. The winner emits a bundle-ready ForecastBundle for the downstream e2e
// engines. This is the ML-capability enrichment surface — NOT an AutoML
// competitor: only the engine's own audited methods, four knobs, deterministic.
//
// Inline-styled to match App.tsx PALETTE. Hits the DSO leaderboard API
// (VITE_DSO_API_BASE ?? "/api/v1"); tier key via X-API-Key.

import { useEffect, useState } from "react";
import PremiumGate from "./PremiumGate";
import { readSsoCookie } from "./sso";

const API_BASE: string =
  (import.meta.env.VITE_DSO_API_BASE as string | undefined) ?? "/api/v1";

// Tiers the leaderboard is included with. Everything else (free / pro / null)
// is gated. The DSO leaderboard API enforces this server-side (require_dso_access
// >= PREMIUM → 403); this set drives the pre-gate so a sub-Premium key sees the
// gate instead of a runnable form that would only fail at submit.
const ENTITLED_TIERS = new Set(["premium", "enterprise", "internal"]);

const PALETTE = {
  bg: "#0f172a",
  bgPanel: "#1e293b",
  border: "#334155",
  text: "#f8fafc",
  textMuted: "#cbd5e1",
  textDim: "#94a3b8",
  textFaint: "#64748b",
  accent: "#fbbf24",
  accentText: "#0f172a",
  link: "#7dd3fc",
  ok: "#86efac",
  okBg: "#14321f",
  okBorder: "#166534",
  warn: "#fcd34d",
  error: "#fca5a5",
  errorBg: "#3f1d1d",
  errorBorder: "#7f1d1d",
  winnerBg: "#1e3a5f",
} as const;

interface LeaderboardEntry {
  method_id: string;
  rank: number;
  is_benchmark: boolean;
  crps: number;
  smape: number | null;
  pinball_q50: number;
  pinball_q90: number;
  wis: number;
  coverage_50: number | null;
  coverage_90: number | null;
  beats_all_benchmarks: boolean | null;
}

interface LeaderboardResult {
  entries: LeaderboardEntry[];
  winner_method_id: string;
  winner_is_benchmark: boolean;
  n_methods: number;
  content_hash: string;
}

// 3-decimal format; "n/a" for null/NaN (smape can be NaN; benchmarks may lack it).
const fmt3 = (v: number | null | undefined): string =>
  v == null || Number.isNaN(v) ? "n/a" : v.toFixed(3);

const SAMPLE_HISTORY = Array.from({ length: 48 }, (_, i) =>
  Math.round(10 + 3 * Math.sin((2 * Math.PI * i) / 7) + (i % 3)),
).join(", ");

// Golden 52-week demand series for the Beauty-CPG golden SKUs.
// Source: generated by golden/generate_inputs.py into
// platforms_os/golden/inputs/dso_demand.json (the "weeks" array per SKU).
// Embedded as a frontend constant because the SPA can't read the repo file at
// runtime. The series are WEEKLY with annual seasonality (beauty_q4_peak /
// summer_peak), so the golden presets set bucket_period="week" and a
// season_length that fits a 52-point backtest (a 13-week quarter — a full
// 52-week season can't be fit from only 52 points).
const GOLDEN_FACE_CRM: number[] = [
  1185, 1211, 1181, 1291, 1283, 1294, 1232, 1305, 1288, 1263, 1286, 1286, 1292,
  1359, 1119, 1247, 1200, 1256, 1350, 1309, 1334, 1266, 1217, 1228, 1326, 1278,
  1198, 1055, 1046, 1052, 1181, 1210, 1079, 1248, 1059, 1184, 1175, 1144, 1091,
  1129, 1357, 1061, 1158, 1032, 1148, 1217, 1412, 1471, 1317, 1640, 1752, 1854,
];
const GOLDEN_SERUM_30: number[] = [
  616, 607, 573, 630, 679, 633, 687, 705, 611, 611, 679, 592, 648, 671, 682,
  640, 617, 693, 600, 667, 490, 574, 555, 639, 714, 591, 556, 536, 666, 608,
  618, 626, 567, 627, 679, 653, 613, 575, 503, 613, 591, 543, 589, 607, 591,
  598, 620, 744, 704, 853, 791, 949,
];
const GOLDEN_SHMP_400: number[] = [
  1388, 1353, 1358, 1441, 1514, 1618, 1557, 1584, 1716, 1539, 1584, 1737, 1610,
  1561, 1377, 1620, 1601, 1577, 1485, 1343, 1483, 1471, 1633, 1494, 1664, 1277,
  1422, 1627, 1185, 1594, 1567, 1400, 1373, 1443, 1367, 1644, 1455, 1396, 1435,
  1413, 1373, 1345, 1610, 1531, 1594, 1563, 1689, 1636, 1976, 2006, 2113, 2214,
];

interface GoldenPreset {
  key: string;
  label: string;
  series: number[];
  horizon: number;
  seasonLength: number;
  forecasterSet: "all" | "statistical" | "ml" | "intermittent" | "fast";
  intermittent: "auto" | "on" | "off";
  nWindows: number;
}

// Sensible, harness-valid knobs for the 52-week golden series: a 4-week
// operational horizon, a 13-week (quarterly) season the weekly data wobbles
// around, the full forecaster panel, and 2 backtest windows.
const GOLDEN_PRESETS: GoldenPreset[] = [
  {
    key: "FACE-CRM",
    label: "Beauty CPG:FACE-CRM (face cream, Q4 peak)",
    series: GOLDEN_FACE_CRM,
    horizon: 4,
    seasonLength: 13,
    forecasterSet: "all",
    intermittent: "off",
    nWindows: 2,
  },
  {
    key: "SERUM-30",
    label: "Beauty CPG:SERUM-30 (serum, Q4 peak)",
    series: GOLDEN_SERUM_30,
    horizon: 4,
    seasonLength: 13,
    forecasterSet: "all",
    intermittent: "off",
    nWindows: 2,
  },
  {
    key: "SHMP-400",
    label: "Beauty CPG:SHMP-400 (shampoo, Q4 peak)",
    series: GOLDEN_SHMP_400,
    horizon: 4,
    seasonLength: 13,
    forecasterSet: "all",
    intermittent: "off",
    nWindows: 2,
  },
];

function parseHistory(raw: string): number[] {
  return raw
    .split(/[\s,]+/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0)
    .map(Number)
    .filter((n) => Number.isFinite(n));
}

export default function LeaderboardView({ token = "" }: { token?: string }) {
  // Pre-gate state. The handed-off SSO key (App-level `token`) decides whether
  // this workbench renders. "open" = show the form; "gated" = show PremiumGate;
  // "checking" = whoami in flight. Fail-soft: default OPEN and only flip to
  // "gated" when whoami CLEARLY returns a sub-Premium tier, so a slow/erroring
  // whoami never locks out a legitimately-entitled user (the API still 403s on
  // Run, so erring open on the UI is safe).
  const [access, setAccess] = useState<"open" | "checking" | "gated">(
    token ? "checking" : "open",
  );
  const [gatedTier, setGatedTier] = useState<string | null>(null);

  useEffect(() => {
    // No handed-off key → leave the form public exactly as before (the form has
    // its own inline tier-key field). Only a present token triggers the check.
    if (!token) {
      setAccess("open");
      setGatedTier(null);
      return;
    }
    setAccess("checking");
    const ctrl = new AbortController();
    // Fail-soft timeout: if whoami stalls, err OPEN rather than spin forever.
    const timer = window.setTimeout(() => ctrl.abort(), 6000);
    fetch(`${API_BASE}/account/whoami`, {
      headers: { "X-API-Key": token },
      signal: ctrl.signal,
    })
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`))))
      .then((d: { tier?: string | null }) => {
        const tier = (d.tier ?? "").toLowerCase();
        if (tier && !ENTITLED_TIERS.has(tier)) {
          setGatedTier(d.tier ?? null);
          setAccess("gated");
        } else {
          // Entitled tier, or an all-null fail-soft response → show the form.
          setAccess("open");
          setGatedTier(null);
        }
      })
      .catch(() => {
        // whoami errored / timed out → never lock out; show the form.
        setAccess("open");
        setGatedTier(null);
      })
      .finally(() => window.clearTimeout(timer));
    return () => {
      window.clearTimeout(timer);
      ctrl.abort();
    };
  }, [token]);

  // W-08: prefill from the signed-in session (App token, else the shared
  // mao_sso cookie) so a signed-in user never has to re-paste a key. The
  // dual-accept gate (require_dso_access) takes a mao_live_ Bearer OR a
  // dso_live_ X-API-Key; authHeaders() routes by prefix.
  const [apiKey, setApiKey] = useState<string>(() => token || readSsoCookie());
  useEffect(() => {
    // Adopt the handed-off session key if the field is still empty.
    if (!apiKey.trim()) {
      const session = token || readSsoCookie();
      if (session) setApiKey(session);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [token]);
  const [historyRaw, setHistoryRaw] = useState(SAMPLE_HISTORY);
  const [horizon, setHorizon] = useState(4);
  const [seasonLength, setSeasonLength] = useState(7);
  const [intermittent, setIntermittent] = useState<"auto" | "on" | "off">("auto");
  const [forecasterSet, setForecasterSet] = useState<
    "all" | "statistical" | "ml" | "intermittent" | "fast"
  >("all");
  const [nWindows, setNWindows] = useState(2);
  // "day" for the synthetic sample; golden presets switch this to "week".
  const [bucketPeriod, setBucketPeriod] = useState<"day" | "week">("day");

  function loadGolden(key: string) {
    const preset = GOLDEN_PRESETS.find((p) => p.key === key);
    if (!preset) return;
    setHistoryRaw(preset.series.join(", "));
    setHorizon(preset.horizon);
    setSeasonLength(preset.seasonLength);
    setForecasterSet(preset.forecasterSet);
    setIntermittent(preset.intermittent);
    setNWindows(preset.nWindows);
    setBucketPeriod("week");
    // Clear any prior run so the user sees a clean slate before Run.
    setStatus("idle");
    setError("");
    setResult(null);
    setReceipt(null);
  }

  const [status, setStatus] = useState<"idle" | "running" | "complete" | "failed">("idle");
  const [error, setError] = useState("");
  const [result, setResult] = useState<LeaderboardResult | null>(null);
  const [runId, setRunId] = useState("");
  const [receipt, setReceipt] = useState<{ calibration_id: string; signature: string } | null>(
    null,
  );

  function authHeaders(json = false): Record<string, string> {
    const h: Record<string, string> = {};
    const key = apiKey.trim();
    if (key) {
      // Cross-engine SSO: a `mao_live_*` Enterprise tier-key authenticates via
      // platform_auth, which expects `Authorization: Bearer` — sending it as
      // `X-API-Key` 401s (mirrors O2C's frontend/src/api/auth.ts fix). Any other
      // key kind (e.g. dso_live_* demo keys) stays on `X-API-Key` as before.
      if (key.startsWith("mao_live_")) {
        h["Authorization"] = `Bearer ${key}`;
      } else {
        h["X-API-Key"] = key;
      }
    }
    if (json) h["Content-Type"] = "application/json";
    return h;
  }

  async function run() {
    setStatus("running");
    setError("");
    setResult(null);
    setReceipt(null);
    // W-07: never a silent no-op — require a key (or sign-in) and say so.
    const key = apiKey.trim();
    if (!key) {
      setError(
        "Enter your tier-key to run the leaderboard: sign in to the engine mesh, " +
          "or paste a mao_live_ / dso_live_ key above.",
      );
      setStatus("failed");
      return;
    }
    const history = parseHistory(historyRaw);
    if (history.length < seasonLength + horizon) {
      setError(`Need at least ${seasonLength + horizon} data points; got ${history.length}.`);
      setStatus("failed");
      return;
    }
    try {
      const submit = await fetch(`${API_BASE}/forecast/leaderboard`, {
        method: "POST",
        headers: authHeaders(true),
        body: JSON.stringify({
          sku_id: "WORKBENCH",
          location_id: "WORKBENCH",
          history,
          bucket_period: bucketPeriod,
          start_date: "2026-01-01",
          horizon,
          season_length: seasonLength,
          intermittent_mode: intermittent,
          forecaster_set: forecasterSet,
          n_windows: nWindows,
          min_train_size: Math.max(seasonLength * 2, history.length - nWindows * horizon - 1),
          seed: 42,
        }),
      });
      if (submit.status === 401) throw new Error("Tier key rejected (401). Check your tier key.");
      if (!submit.ok) throw new Error(`Submit failed: ${submit.status}`);
      const { run_id } = await submit.json();
      setRunId(run_id);

      // Poll until complete.
      for (let i = 0; i < 120; i++) {
        await new Promise((res) => setTimeout(res, 1500));
        const poll = await fetch(`${API_BASE}/forecast/leaderboard/${run_id}`, {
          headers: authHeaders(),
        });
        const body = await poll.json();
        if (body.status === "complete") {
          setResult(body.result as LeaderboardResult);
          setStatus("complete");
          return;
        }
        if (body.status === "failed") {
          throw new Error(body.error ?? "run failed");
        }
      }
      throw new Error("timed out waiting for the run");
    } catch (e) {
      setError((e as Error).message);
      setStatus("failed");
    }
  }

  async function fetchReceipt() {
    if (!runId) return;
    try {
      const r = await fetch(`${API_BASE}/forecast/leaderboard/${runId}/receipt`, {
        headers: authHeaders(),
      });
      if (!r.ok) throw new Error(`receipt failed: ${r.status}`);
      const rec = await r.json();
      setReceipt({ calibration_id: rec.calibration_id, signature: rec.signature });
    } catch (e) {
      setError((e as Error).message);
    }
  }

  // Native Excel workbook: ranked methods + the winner's per-horizon forecasted
  // values + reproducibility summary. Gated like the other leaderboard reads,
  // so it carries the tier key; downloads the blob the API streams back.
  async function downloadXlsx() {
    if (!runId) return;
    try {
      const r = await fetch(`${API_BASE}/forecast/leaderboard/${runId}/xlsx`, {
        headers: authHeaders(),
      });
      if (!r.ok) throw new Error(`export failed: ${r.status}`);
      const blob = await r.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `leaderboard_${runId}.xlsx`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (e) {
      setError((e as Error).message);
    }
  }

  // SimOS arrivals contract: the winning forecast as a SimOS-consumable
  // arrivals.schedule YAML. Humans audit the .xlsx; SimOS ingests this YAML.
  async function downloadArrivalsYaml() {
    if (!runId) return;
    try {
      const r = await fetch(`${API_BASE}/forecast/leaderboard/${runId}/arrivals.yaml`, {
        headers: authHeaders(),
      });
      if (!r.ok) throw new Error(`SimOS YAML export failed: ${r.status}`);
      const blob = await r.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `arrivals_${runId}.yaml`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (e) {
      setError((e as Error).message);
    }
  }

  // Sub-Premium handed-off key → clean pre-gate instead of the runnable form.
  if (access === "gated") {
    return <PremiumGate tier={gatedTier} />;
  }

  // whoami in flight → a quiet placeholder so a sub-Premium user doesn't see the
  // full form flash before the gate resolves. Resolves to "open"/"gated" fast.
  if (access === "checking") {
    return (
      <section style={{ padding: "2.5rem 1.5rem", maxWidth: 920, margin: "0 auto" }}>
        <p style={{ color: PALETTE.textDim, fontSize: "0.85rem" }}>Checking access…</p>
      </section>
    );
  }

  return (
    <section style={{ padding: "2rem 1.5rem", maxWidth: 920, margin: "0 auto" }}>
      <h2 style={{ margin: 0, fontSize: "1.5rem", color: PALETTE.text }}>
        Forecaster leaderboard
      </h2>
      <p style={{ marginTop: 8, fontSize: "0.9rem", color: PALETTE.textDim, lineHeight: 1.6, maxWidth: 700 }}>
        Run every registered forecaster on your demand history and rank them{" "}
        <strong style={{ color: PALETTE.textMuted }}>probabilistically</strong>, by CRPS and
        interval coverage, not point error. Each candidate is gated against the naive
        benchmarks: a model can rank #1 and still be flagged{" "}
        <em>"doesn't beat naive."</em> The winner ships a bundle-ready forecast into
        PlanningOS / SimOS / O2C.
      </p>
      <p style={{ marginTop: 6, fontSize: "0.78rem", color: PALETTE.textFaint, lineHeight: 1.6, maxWidth: 700 }}>
        <strong style={{ color: PALETTE.textDim }}>CRPS</strong>: probabilistic accuracy of the
        whole forecast distribution (lower is better).{" "}
        <strong style={{ color: PALETTE.textDim }}>Coverage</strong>: how often the actual fell
        inside the predicted band (a 90% band should contain about 90%).{" "}
        <strong style={{ color: PALETTE.textDim }}>Beats naive</strong>: whether the model improved
        on a simple seasonal-naive baseline. Full definitions in the{" "}
        <a href="https://edu.sim-os.ai/glossary" style={{ color: PALETTE.link }}>glossary</a>.
      </p>

      {/* Config panel */}
      <div style={panelStyle}>
        <label style={labelStyle}>Tier key (auto-filled from your sign-in)</label>
        <input
          type="password"
          placeholder="mao_live_… or dso_live_…"
          value={apiKey}
          onChange={(e) => setApiKey(e.target.value)}
          style={inputStyle}
        />
        <p style={{ margin: "4px 0 0 0", fontSize: "0.7rem", color: PALETTE.textFaint }}>
          {apiKey.trim()
            ? "Using your signed-in tier-key (a mao_live_ key via SSO, or a dso_live_ demo key)."
            : "Required on the live API. Sign in to the engine mesh, or paste a mao_live_ / dso_live_ key."}
        </p>

        <div style={{ marginTop: 12 }}>
          <label style={labelStyle}>Load golden example (Beauty CPG)</label>
          <select
            value=""
            onChange={(e) => loadGolden(e.target.value)}
            style={{ ...inputStyle, width: 320, maxWidth: "100%" }}
            title="Fill the history + knobs with a golden 52-week demand series, then press Run leaderboard."
          >
            <option value="" disabled>
              Choose a golden SKU…
            </option>
            {GOLDEN_PRESETS.map((p) => (
              <option key={p.key} value={p.key}>
                {p.label}
              </option>
            ))}
          </select>
          <p style={{ margin: "4px 0 0 0", fontSize: "0.7rem", color: PALETTE.textFaint }}>
            One click loads a 52-week weekly series + sensible knobs (horizon 4,
            season 13, full panel), then press Run leaderboard.
          </p>
        </div>

        <label style={{ ...labelStyle, marginTop: 12 }}>
          Demand history (comma / newline separated)
        </label>
        <textarea
          value={historyRaw}
          onChange={(e) => setHistoryRaw(e.target.value)}
          style={{ ...inputStyle, height: 90, fontFamily: "monospace", fontSize: "0.75rem" }}
        />
        <p style={{ margin: "4px 0 0 0", fontSize: "0.7rem", color: PALETTE.textFaint }}>
          {parseHistory(historyRaw).length} points parsed
        </p>

        <div style={{ display: "flex", flexWrap: "wrap", gap: 16, marginTop: 14 }}>
          <Knob label="Horizon" value={horizon} setValue={setHorizon} min={1}
            title="How many future periods to forecast and score." />
          <Knob label="Season length" value={seasonLength} setValue={setSeasonLength} min={1}
            title="The repeating cycle length (e.g. 7 for a weekly pattern in daily data, 12 for monthly)." />
          <Knob label="Backtest windows" value={nWindows} setValue={setNWindows} min={1}
            title="How many walk-forward test windows to average each score over." />
          <div>
            <label style={labelStyle}>Intermittent</label>
            <select
              value={intermittent}
              onChange={(e) => setIntermittent(e.target.value as "auto" | "on" | "off")}
              style={{ ...inputStyle, width: 110 }}
              title="For sparse / zero-heavy demand: 'on' uses intermittent methods (Croston/TSB/SBA)."
            >
              <option value="auto">auto</option>
              <option value="on">on</option>
              <option value="off">off</option>
            </select>
          </div>
          <div>
            <label style={labelStyle}>Forecaster set</label>
            <select
              value={forecasterSet}
              onChange={(e) =>
                setForecasterSet(
                  e.target.value as "all" | "statistical" | "ml" | "intermittent" | "fast",
                )
              }
              style={{ ...inputStyle, width: 150 }}
              title="Narrow the panel to cut runtime. Benchmarks always run."
            >
              <option value="all">all (full panel)</option>
              <option value="statistical">statistical (ets/arima/theta/ces)</option>
              <option value="ml">ml (gbm)</option>
              <option value="intermittent">intermittent (croston/tsb/sba)</option>
              <option value="fast">fast (ets/theta)</option>
            </select>
          </div>
        </div>

        <button
          onClick={run}
          disabled={status === "running"}
          style={{
            marginTop: 16,
            padding: "0.55rem 1.2rem",
            backgroundColor: PALETTE.accent,
            color: PALETTE.accentText,
            border: "none",
            borderRadius: 4,
            cursor: status === "running" ? "wait" : "pointer",
            fontWeight: 700,
            fontSize: "0.9rem",
          }}
        >
          {status === "running" ? "Running leaderboard…" : "▶ Run leaderboard"}
        </button>
        {status === "running" && (
          <p style={{ margin: "8px 0 0 0", fontSize: "0.78rem", color: PALETTE.textDim }}>
            Fitting every method through walk-forward backtest (GBM trains 7 quantile
            models per window, so this can take a minute).
          </p>
        )}
        {error && (
          <div
            style={{
              marginTop: 12,
              padding: "0.6rem 0.8rem",
              backgroundColor: PALETTE.errorBg,
              border: `1px solid ${PALETTE.errorBorder}`,
              borderRadius: 6,
              color: PALETTE.error,
              fontSize: "0.82rem",
            }}
          >
            {error}
          </div>
        )}
      </div>

      {result && (
        <Results
          result={result}
          receipt={receipt}
          onFetchReceipt={fetchReceipt}
          onDownloadXlsx={downloadXlsx}
          onDownloadYaml={downloadArrivalsYaml}
        />
      )}
    </section>
  );
}

function Results({
  result,
  receipt,
  onFetchReceipt,
  onDownloadXlsx,
  onDownloadYaml,
}: {
  result: LeaderboardResult;
  receipt: { calibration_id: string; signature: string } | null;
  onFetchReceipt: () => void;
  onDownloadXlsx: () => void;
  onDownloadYaml: () => void;
}) {
  const winnerEntry = result.entries.find((e) => e.method_id === result.winner_method_id);
  return (
    <div style={{ marginTop: 24 }}>
      {/* Winner banner */}
      <div
        style={{
          padding: "0.9rem 1.1rem",
          borderRadius: 8,
          backgroundColor: result.winner_is_benchmark ? PALETTE.errorBg : PALETTE.okBg,
          border: `1px solid ${result.winner_is_benchmark ? PALETTE.errorBorder : PALETTE.okBorder}`,
          marginBottom: 16,
        }}
      >
        {result.winner_is_benchmark ? (
          <p style={{ margin: 0, color: PALETTE.error, fontSize: "0.9rem" }}>
            ⚠ No forecaster beat the naive benchmarks. Recommending the safest baseline:{" "}
            <strong>{result.winner_method_id}</strong>. Your series may be too short or too
            noisy for a model to add value. That's an honest answer, not a failure.
          </p>
        ) : (
          <p style={{ margin: 0, color: PALETTE.ok, fontSize: "0.95rem" }}>
            ✓ Winner: <strong>{result.winner_method_id}</strong>, beats all naive benchmarks
            (CRPS {winnerEntry?.crps.toFixed(3)}, 90% coverage{" "}
            {winnerEntry?.coverage_90 != null ? `${(winnerEntry.coverage_90 * 100).toFixed(0)}%` : "n/a"}).
          </p>
        )}
      </div>

      {/* Ranked table */}
      <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "0.82rem" }}>
        <thead>
          <tr style={{ color: PALETTE.textDim, textAlign: "left" }}>
            <th style={thStyle}>#</th>
            <th style={thStyle}>Method</th>
            <th style={thStyle}>CRPS ↓</th>
            <th style={thStyle}>sMAPE ↓</th>
            <th style={thStyle}>Pinball q50 ↓</th>
            <th style={thStyle}>Pinball q90 ↓</th>
            <th style={thStyle}>WIS ↓</th>
            <th style={thStyle}>50% cov</th>
            <th style={thStyle}>90% cov</th>
            <th style={thStyle}>Trust</th>
          </tr>
        </thead>
        <tbody>
          {result.entries.map((e) => {
            const isWinner = e.method_id === result.winner_method_id;
            return (
              <tr
                key={e.method_id}
                style={{
                  backgroundColor: isWinner ? PALETTE.winnerBg : "transparent",
                  borderBottom: `1px solid ${PALETTE.border}`,
                }}
              >
                <td style={tdStyle}>{e.rank}</td>
                <td style={{ ...tdStyle, fontFamily: "monospace", fontWeight: isWinner ? 700 : 400 }}>
                  {e.method_id}
                  {e.is_benchmark && (
                    <span style={{ color: PALETTE.textFaint, fontSize: "0.7rem" }}> (benchmark)</span>
                  )}
                </td>
                <td style={tdStyle}>{e.crps.toFixed(3)}</td>
                <td style={tdStyle}>{fmt3(e.smape)}</td>
                <td style={tdStyle}>{fmt3(e.pinball_q50)}</td>
                <td style={tdStyle}>{fmt3(e.pinball_q90)}</td>
                <td style={tdStyle}>{fmt3(e.wis)}</td>
                <td style={tdStyle}>
                  {e.coverage_50 != null ? `${(e.coverage_50 * 100).toFixed(0)}%` : "n/a"}
                </td>
                <td style={tdStyle}>
                  {e.coverage_90 != null ? `${(e.coverage_90 * 100).toFixed(0)}%` : "n/a"}
                </td>
                <td style={tdStyle}>
                  {e.is_benchmark ? (
                    <span style={{ color: PALETTE.textFaint }}>gate</span>
                  ) : e.beats_all_benchmarks ? (
                    <span style={badge(PALETTE.ok, PALETTE.okBg, PALETTE.okBorder)}>beats naive</span>
                  ) : (
                    <span style={badge(PALETTE.error, PALETTE.errorBg, PALETTE.errorBorder)}>
                      below naive
                    </span>
                  )}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      {/* Reproducibility + receipt */}
      <div style={{ marginTop: 16, display: "flex", alignItems: "center", gap: 16, flexWrap: "wrap" }}>
        <span style={{ fontSize: "0.75rem", color: PALETTE.textDim }}>
          {result.n_methods} methods · reproducibility hash{" "}
          <code style={{ color: PALETTE.textMuted }}>{result.content_hash}</code>
        </span>
        <button
          onClick={onFetchReceipt}
          style={{
            padding: "5px 12px",
            fontSize: "0.78rem",
            backgroundColor: PALETTE.link,
            color: PALETTE.bg,
            border: "none",
            borderRadius: 4,
            cursor: "pointer",
            fontWeight: 700,
          }}
        >
          Get signed receipt
        </button>
        <button
          onClick={onDownloadXlsx}
          title="Download the leaderboard (ranked methods + the winner's per-horizon forecasted values) as a native Excel workbook"
          style={{
            padding: "5px 12px",
            fontSize: "0.78rem",
            backgroundColor: "transparent",
            color: PALETTE.text,
            border: `1px solid ${PALETTE.border}`,
            borderRadius: 4,
            cursor: "pointer",
            fontWeight: 700,
          }}
        >
          ⬇ Download Excel
        </button>
        <button
          onClick={onDownloadYaml}
          title="Download the winning forecast as a SimOS arrivals.schedule YAML (the DSO→SimOS contract SimOS consumes directly)"
          style={{
            padding: "5px 12px",
            fontSize: "0.78rem",
            backgroundColor: "transparent",
            color: PALETTE.text,
            border: `1px solid ${PALETTE.border}`,
            borderRadius: 4,
            cursor: "pointer",
            fontWeight: 700,
          }}
        >
          ⬇ SimOS YAML
        </button>
      </div>
      {receipt && (
        <div
          style={{
            marginTop: 10,
            padding: "0.6rem 0.8rem",
            backgroundColor: PALETTE.bgPanel,
            border: `1px solid ${PALETTE.border}`,
            borderRadius: 6,
            fontSize: "0.75rem",
            color: PALETTE.textMuted,
            wordBreak: "break-all",
          }}
        >
          <strong style={{ color: PALETTE.ok }}>Signed ✓</strong> {receipt.calibration_id}
          <br />
          <span style={{ color: PALETTE.textFaint }}>HMAC signature:</span> {receipt.signature}
        </div>
      )}
    </div>
  );
}

function Knob({
  label,
  value,
  setValue,
  min,
  title,
}: {
  label: string;
  value: number;
  setValue: (n: number) => void;
  min: number;
  title?: string;
}) {
  return (
    <div title={title}>
      <label style={labelStyle}>{label}</label>
      <input
        type="number"
        min={min}
        value={value}
        onChange={(e) => setValue(Math.max(min, Number(e.target.value) || min))}
        style={{ ...inputStyle, width: 90 }}
      />
    </div>
  );
}

const panelStyle: React.CSSProperties = {
  marginTop: 20,
  padding: "1.25rem",
  backgroundColor: PALETTE.bgPanel,
  border: `1px solid ${PALETTE.border}`,
  borderRadius: 8,
};

const labelStyle: React.CSSProperties = {
  display: "block",
  fontSize: "0.72rem",
  color: PALETTE.textDim,
  marginBottom: 4,
  textTransform: "uppercase",
  letterSpacing: "0.04em",
};

const inputStyle: React.CSSProperties = {
  width: "100%",
  padding: "0.45rem",
  borderRadius: 4,
  border: `1px solid ${PALETTE.border}`,
  backgroundColor: PALETTE.bg,
  color: PALETTE.text,
  fontSize: "0.85rem",
  boxSizing: "border-box",
};

const thStyle: React.CSSProperties = {
  padding: "0.4rem 0.6rem",
  borderBottom: `1px solid ${PALETTE.border}`,
  fontWeight: 600,
};

const tdStyle: React.CSSProperties = { padding: "0.45rem 0.6rem", color: PALETTE.text };

function badge(color: string, bg: string, border: string): React.CSSProperties {
  return {
    fontSize: "0.68rem",
    fontWeight: 700,
    padding: "2px 7px",
    borderRadius: 3,
    color,
    backgroundColor: bg,
    border: `1px solid ${border}`,
  };
}
