"""DEPRECATED-AS-CANONICAL — types live in ``ops_schemas`` (top-level
shared package at ``platforms_os/packages/ops_schemas/``).

This shim re-exports the promoted types so every pre-existing
``from demand_signal_os.ops_schemas import ...`` site continues to work
byte-for-byte. New consumers should import from ``ops_schemas`` directly
to avoid the transitive DSO dependency cost.

Promoted 2026-06-08 per CONSTITUTION §8 policy. Trigger met by the
PlanningOS production wire-up (Phase D) + the SimOS arrival adapter
(Phase B) — both need typed access to the boundary language without
pulling in scipy / lightgbm / statsforecast / pandas.

Install order in dev:
    pip install -e platforms_os/packages/ops_schemas
    pip install -e platforms_os/Demand_Signal_OS
"""

from ops_schemas import (  # re-export
    PIR,
    SKU,
    ArchetypeTag,
    BaseStockParameters,
    CalibrationError,
    CalibrationKind,
    CalibrationMetric,
    CalibrationReceipt,
    CalibrationReference,
    CalibrationReferenceMeta,
    CalibrationRejection,
    CalibrationState,
    CalibrationStatus,
    Calibrator,
    CensoringFlag,
    CheckIndependence,
    DemandActual,
    DemandSignal,
    EventLogReference,
    ForecastAccuracy,
    ForecastActualsReference,
    ForecastBundle,
    Forecaster,
    ForecastFallbackStrategy,
    ForecastProvenance,
    FreshnessPolicy,
    FreshnessPolicyKind,
    IncompleteCalibration,
    InvalidReferenceData,
    InventoryPolicy,
    Location,
    MetricGate,
    NewsvendorParameters,
    PhaseResult,
    PlanActualsReference,
    PolicyParameters,
    ProbabilisticDistribution,
    PropagationRule,
    ProvenanceEnvelope,
    QRParameters,
    Quantiles,
    ReorderTrigger,
    SimulationActualsReference,
    SSParameters,
    TimeBucket,
    ToleranceKind,
    WorkbookReference,
    canonical_receipt_json,
    compose_inputs_hash,
    derive_test_mode_secret,
    sign_receipt,
    verify_receipt,
)

__all__ = [
    "PIR",
    "SKU",
    "ArchetypeTag",
    "BaseStockParameters",
    "CalibrationError",
    "CalibrationKind",
    "CalibrationMetric",
    "CalibrationReceipt",
    "CalibrationReference",
    "CalibrationReferenceMeta",
    "CalibrationRejection",
    "CalibrationState",
    "CalibrationStatus",
    "Calibrator",
    "CensoringFlag",
    "CheckIndependence",
    "DemandActual",
    "DemandSignal",
    "EventLogReference",
    "ForecastAccuracy",
    "ForecastActualsReference",
    "ForecastBundle",
    "Forecaster",
    "ForecastFallbackStrategy",
    "ForecastProvenance",
    "FreshnessPolicy",
    "FreshnessPolicyKind",
    "IncompleteCalibration",
    "InvalidReferenceData",
    "InventoryPolicy",
    "Location",
    "MetricGate",
    "NewsvendorParameters",
    "PhaseResult",
    "PlanActualsReference",
    "PolicyParameters",
    "ProbabilisticDistribution",
    "PropagationRule",
    "ProvenanceEnvelope",
    "QRParameters",
    "Quantiles",
    "ReorderTrigger",
    "SimulationActualsReference",
    "SSParameters",
    "TimeBucket",
    "ToleranceKind",
    "WorkbookReference",
    "canonical_receipt_json",
    "compose_inputs_hash",
    "derive_test_mode_secret",
    "sign_receipt",
    "verify_receipt",
]
